import express from 'express';
import { UserController } from './user.controller';
import Auth from '../../middlewares/Auth';
import { ENUM_USER_ROLE } from '../../../enum/user';
const router = express.Router();
router.get('/', Auth(ENUM_USER_ROLE.ADMIN), UserController.getAllUser);
router.get('/:id', Auth(ENUM_USER_ROLE.ADMIN), UserController.getSingleUser);
router.patch('/:id', Auth(ENUM_USER_ROLE.ADMIN), UserController.updateUser);
router.delete('/:id', Auth(ENUM_USER_ROLE.ADMIN), UserController.deleteUser);
export const UserRoutes = router;
